oro_email_email_view:
    type: entity
    class: OroEmailBundle:Email
    permission: VIEW
    group_name: ""

oro_email_email_create:
    type: entity
    class: OroEmailBundle:EmailUser
    permission: CREATE
    group_name: ""

oro_email_email_edit:
    type: entity
    class: OroEmailBundle:Email
    permission: EDIT
    group_name: ""

oro_email_email_user_edit:
    type: entity
    class: OroEmailBundle:EmailUser
    permission: EDIT
    group_name: ""

oro_email_mailbox_view:
    type: entity
    class: OroEmailBundle:Mailbox
    permission: VIEW
    group_name: ""

oro_email_mailbox_delete:
    type: entity
    class: OroEmailBundle:Bailbox
    permission: DELETE
    group_name: ""

oro_email_mailbox_create:
    type: entity
    class: OroEmailBundle:Bailbox
    permission: CREATE
    group_name: ""

oro_email_mailbox_edit:
    type: entity
    class: OroEmailBundle:Bailbox
    permission: EDIT
    group_name: ""
