oro_email_email_view:
    type: entity
    class: OroEmailBundle:Email
    permission: VIEW
    group_name: ""

oro_email_email_create:
    type: entity
    class: OroEmailBundle:UserEmailOwner
    permission: CREATE
    group_name: ""

oro_email_email_edit:
    type: entity
    class: OroEmailBundle:Email
    permission: EDIT
    group_name: ""
