js:
  'email':
      - '@OroEmailBundle/Resources/public/js/views/templates.updater.js'
      - '@OroEmailBundle/Resources/public/js/models/templates.updater.js'
      - '@OroEmailBundle/Resources/public/js/collections/templates.updater.js'
css:
    'email':
      - '@OroEmailBundle/Resources/public/css/style.css'
