datagrid:
    base-email-grid:
        source:
            type: orm
            query:
                select:
                    - partial eu.{id, email}
                    - CASE WHEN eu.seen = true THEN 0 ELSE 1 END as is_new
                from:
                    - { table: OroEmailBundle:EmailUser, alias: eu }
                join:
                    left:
                        -
                            join: eu.email
                            alias: e
                        -
                            join: e.thread
                            alias: thread
                        -
                            join: e.recipients
                            alias: recipients
                        -
                            join: e.recipients
                            alias: r_to
                            conditionType: WITH
                            condition: r_to.type = 'to'
                        -
                            join: e.recipients
                            alias: r_cc_bcc
                            conditionType: WITH
                            condition: r_cc_bcc.type = 'cc' OR r_cc_bcc.type = 'bcc'
                        -
                            join: eu.folder
                            alias: f
                groupBy: eu.id, e.sentAt
        columns:
            contacts:
                data_name: email.contacts
                type: twig
                label: oro.email.contact.label
                frontend_type: html
                template: OroEmailBundle:Email:Datagrid/Property/contacts.html.twig
            subject:
                data_name: email.subject
                type: twig
                label: oro.email.subject.label
                frontend_type: html
                template: OroEmailBundle:Email:Datagrid/Property/subject.html.twig
            attachments:
                data_name: email.attachments
                type: twig
                label:
                frontend_type: html
                template: OroEmailBundle:Email:Datagrid/Property/attachments.html.twig
            sentAt:
                data_name: email.sentAt
                type: twig
                label: oro.email.date.label
                frontend_type: html
                template: OroEmailBundle:Email:Datagrid/Property/date.html.twig
        properties:
            id: ~
        sorters:
            columns:
                subject:  { data_name: e.subject }
                sentAt:   { data_name: e.sentAt }
            default: { sentAt: %oro_datagrid.extension.orm_sorter.class%::DIRECTION_DESC }
        options:
            entityHint: email

    simplified-email-grid:
        extends: base-email-grid
        options:
            toolbarOptions:
                turnOffToolbarRecordsNumber: 5
                addResetAction: false

    email-grid:
        extends: base-email-grid
        source:
            query:
                where:
                    and:
                        - e.head = true
#                        - f.type IN ('%oro_email.email_folder.model.class%::INBOX', '%oro_email.email_folder.model.class%::SENT')
        filters:
            columns:
                subject: { type: string,   data_name: e.subject }
                to:      { type: string,   data_name: r_to.name, label: oro.email.to.label }
                ccBcc:   { type: string,   data_name: r_cc_bcc.name, label: oro.email.cc_bcc.label }
                date:    { type: datetime, data_name: e.sentAt, label: oro.email.date_time.label }
                folder:
                    label: oro.email.folder_type.label
                    type: choice
                    options:
                        field_options:
                            multiple: true
                            choices:
                                inbox: oro.email.folder_type.inbox
                                sent: oro.email.folder_type.sent
                                other: oro.email.folder_type.other
                                drafts: oro.email.folder_type.drafts
                                spam: oro.email.folder_type.spam
                                trash: oro.email.folder_type.trash
                    data_name: f.type
                folders:
                    type: multiselect-originfolder
                    data_name: f.id
                    label: oro.email.folders.label
                    options:
                        field_options:
                            multiple: true
                            choices: @oro_email.datagrid.origin_folder.provider->getListTypeChoices
                is_new:
                    label: oro.email.status.label
                    type: choice
                    options:
                        field_options:
                            choices:
                                false: oro.email.status.unread.label
                                true: oro.email.status.read.label
                    data_name: eu.seen
        views_list : @oro_email.emailfolder.datagrid_view_list

    activity-email-grid:
        extends: email-grid

    user-email-grid:
        extends: email-grid

        properties:
            id: ~
            email.id: ~
            view_thread_link:
                type: url
                route: oro_email_thread_view
                params: { id: email.id }
            toggle_seen_link:
                type: url
                route: oro_email_toggle_seen
                params: { id: id }
            row_class_name:
                type: callback
                className: 'email-row-is-readed'
                callable: @oro_email.helper.datagrid.emails->getReadedRowClosure

        actions:
            view_thread:
                type: navigate
                label: oro.grid.action.view
                link: view_thread_link
                icon: eye-open
                rowAction: true
            mark_as_read:
                type: ajax
                label: oro.email.datagrid.emails.action.mark_as_read
                link:  toggle_seen_link
                icon: check
                defaultMessages:
                    success: oro.email.action.success_mark_read
                    error: oro.email.action.error
            mark_as_unread:
                type: ajax
                label: oro.email.datagrid.emails.action.mark_as_unread
                link:  toggle_seen_link
                icon: minus
                defaultMessages:
                    success: oro.email.action.success_mark_unread
                    error: oro.email.action.error
        action_configuration: @oro_email.helper.datagrid.emails->getActionConfigurationClosure
        mass_actions:
            emailmarkread:
                type: emailmarkread
                entity_name: %oro_email.email_user.entity.class%
                data_identifier: eu.id
                label: oro.email.datagrid.emails.action.mark_as_read
                icon: check
            emailmarkunread:
                type: emailmarkunread
                entity_name: %oro_email.email_user.entity.class%
                data_identifier: eu.id
                label: oro.email.datagrid.emails.action.mark_as_unread
                icon: minus

    dashboard-recent-emails-grid:
        source:
            type: orm
            query:
                select:
                    - partial e.{ id, subject, sentAt }
                    - partial eu.{ id, receivedAt, email }
                    - a
                    - CASE WHEN eu.seen = true THEN 0 ELSE 1 END as is_new
                from:
                    - { table: OroEmailBundle:EmailUser, alias: eu }
                join:
                    left:
                        -
                            join: eu.email
                            alias: e
                    inner:
                        - { join: eu.folder, alias: f }
                        - { join: f.origin, alias: o }
                        - { join: e.fromEmailAddress, alias: a }
                where:
                    and:
                        - o.id IN (:origin_ids)
        properties:
            id: ~
            row_class_name:
                type: callback
                className: 'email-row-is-readed'
                callable: @oro_email.helper.datagrid.emails->getReadedRowClosure
        options:
            entityHint: email
            toolbarOptions:
                hide: true
                pageSize:
                    items: [10]
                    default_per_page: 10

    dashboard-recent-emails-inbox-grid:
        extends: dashboard-recent-emails-grid
        source:
            query:
                where:
                    and:
                        - f.type IN ('%oro_email.email_folder.model.class%::INBOX', '%oro_email.email_folder.model.class%::OTHER')
        columns:
            receivedAt:
                type: twig
                label: oro.email.received_at.label
                frontend_type: html
                template: OroEmailBundle:Email:Datagrid/Property/date_long.html.twig
            fromEmailExpression:
                type: twig
                label: oro.email.from_name.label
                frontend_type: html
                template: OroEmailBundle:Email:Datagrid/Property/from.html.twig
            subject:
                data_name: email.subject
                type: twig
                label: oro.email.subject.label
                frontend_type: html
                template: OroEmailBundle:Email:Datagrid/Property/subject.html.twig
        sorters:
            columns:
                fromEmailExpression: { data_name: fromEmailExpression }
                receivedAt:  { data_name: eu.receivedAt }
            default:
                receivedAt: %oro_datagrid.extension.orm_sorter.class%::DIRECTION_DESC

    dashboard-recent-emails-sent-grid:
        extends: dashboard-recent-emails-grid
        source:
            query:
                where:
                    and:
                        - f.type = '%oro_email.email_folder.model.class%::SENT'
        columns:
            sentAt:
                data_name: email.sentAt
                label: oro.email.sent_at.label
                frontend_type: datetime
            recipients:
                data_name: email.recipients
                type: twig
                label: oro.email.recipients.label
                frontend_type: html
                template: OroEmailBundle:Email:Datagrid/Property/recipients.html.twig
            subject:
                data_name: email.subject
                type: twig
                label: oro.email.subject.label
                frontend_type: html
                template: OroEmailBundle:Email:Datagrid/Property/subject.html.twig
        sorters:
            columns:
                sentAt:  { data_name: e.sentAt }
            default:
                sentAt: %oro_datagrid.extension.orm_sorter.class%::DIRECTION_DESC

    dashboard-recent-emails-new-grid:
        extends: dashboard-recent-emails-grid
        source:
            query:
                where:
                    and:
                        - eu.seen = false
        columns:
            receivedAt:
                type: twig
                label: oro.email.received_at.label
                frontend_type: html
                template: OroEmailBundle:Email:Datagrid/Property/date_long.html.twig
            fromEmailExpression:
                type: twig
                label: oro.email.from_name.label
                frontend_type: html
                template: OroEmailBundle:Email:Datagrid/Property/from.html.twig
            subject:
                data_name: email.subject
                type: twig
                label: oro.email.subject.label
                frontend_type: html
                template: OroEmailBundle:Email:Datagrid/Property/subject.html.twig
        sorters:
            columns:
                fromEmailExpression: { data_name: fromEmailExpression }
                receivedAt:  { data_name: eu.receivedAt }
            default:
                receivedAt: %oro_datagrid.extension.orm_sorter.class%::DIRECTION_DESC

    email-templates:
        source:
            type: orm
            acl_resource: oro_email_emailtemplate_index
            query:
                select:
                    - t.id
                    - t.entityName
                    - t.name
                    - t.type
                    - t.isSystem
                from:
                    - { table: %oro_email.emailtemplate.entity.class%, alias: t }

        columns:
            entityName:
                label:          oro.email.emailtemplate.entity_name.label
                type:           twig
                template:       OroEntityBundle:Datagrid:Property/entity.html.twig
                frontend_type:  html
                context:
                    entity_provider: @oro_entity.entity_provider
            name:
                label:          oro.email.emailtemplate.name.label
            type:
                frontend_type:  select
                label:          oro.email.emailtemplate.type.label
                choices:        @oro_email.emailtemplate.datagrid_helper->getTypeChoices
            isSystem:
                frontend_type:  boolean
                label:          oro.email.emailtemplate.is_system.label
        properties:
            id: ~
            update_link:
                type: url
                route: oro_email_emailtemplate_update
                params: [ id ]
            clone_link:
                type: url
                route: oro_email_emailtemplate_clone
                params: [ id ]
            delete_link:
                type: url
                route: oro_api_delete_emailtemplate
                params: [ id ]

        filters:
            columns:
                entityName:
                    type:      choice
                    data_name: t.entityName
                    null_value: _empty_
                    options:
                        field_options:
                            multiple:       true
                            choices:        @oro_email.emailtemplate.datagrid_helper->getEntityNames
                            translatable_options: false
                name:
                    type:      string
                    data_name: t.name
                type:
                    type:            choice
                    data_name:       t.type
                    options:
                        field_options:
                            choices: @oro_email.emailtemplate.datagrid_helper->getTypeChoices

                isSystem:
                    type:           boolean
                    data_name:      t.isSystem

        sorters:
            columns:
                name:     { data_name: t.name }
                type:     { data_name: t.type }
                isSystem: { data_name: t.isSystem }

        actions:
            update:
                type:         navigate
                label:        oro.grid.action.update
                link:         update_link
                icon:         edit
                acl_resource: oro_email_emailtemplate_update
                rowAction:    true
            clone:
                type:         navigate
                label:        oro.grid.action.clone
                link:         clone_link
                icon:         copy
                acl_resource: oro_email_emailtemplate_create
            delete:
                type:         delete
                label:        oro.grid.action.delete
                acl_resource: oro_email_emailtemplate_delete
                icon:         trash
                link:         delete_link
        options:
            entity_pagination: true
        action_configuration: @oro_email.emailtemplate.datagrid_helper->getActionConfigurationClosure
        views_list : @oro_email.emailtemplate.datagrid_view_list
        options: { entityHint: email template }
