datagrid:
    email-grid:
        source:
            acl_resource: oro_email_view
            type: orm
            query:
                select:
                    - e.id
                    - e.fromName
                    - e.fromEmailAddress
                    - e.subject
                    - e.sentAt
                    - e.recipients
                    - a
                from:
                    - { table: OroEmailBundle:Email, alias: e }
                join:
                    inner:
                        from_email_address:
                            join: e.fromEmailAddress
                            alias: a

        columns:
            id:
                type: field
            fromEmailAddress:
                type: twig
                template: OroEmailBundle:Email:Datagrid/Property/from.html.twig
            subject:
                type: twig
                template: OroEmailBundle:Email:Datagrid/Property/subject.html.twig
            sentAt:
                type: field
            recipients:
                type: twig
                template: OroEmailBundle:Email:Datagrid/Property/recipients.html.twig

        properties:

        sorters:
            columns:
                subject:
                    data_name: e.subject
                sentAt:
                    data_name: u.sentAt
            default:
                sentAt: %oro_grid.extension.orm_sorter.class%::DIRECTION_DESC

        filters:
            columns:
                fromEmailAddress:
                    type: string
                    data_name: e.fromEmailAddress
                subject:
                    type: string
                    data_name: e.subject
                sentAt:
                    type: string
                    data_name: e.sentAt
