parameters:
    oro_email.emailtemplate.datagrid_manager.class: Oro\Bundle\EmailBundle\Datagrid\EmailTemplateDatagridManager
    oro_email.user_email_datagrid_manager.class: Oro\Bundle\EmailBundle\Datagrid\EmailDatagridManager

services:
    oro_email.emailtemplate.datagrid_manager:
        class: %oro_email.emailtemplate.datagrid_manager.class%
        arguments: [%oro_config.entities%]
        tags:
            - name: oro_grid.datagrid.manager
              datagrid_name: emailtemplate
              entity_name: %oro_email.emailtemplate.entity.class%
              entity_hint: email template
              route_name: oro_email_emailtemplate_index
              identifier_field: "id"

    oro_email.email_datagrid_manager:
        class: %oro_email.user_email_datagrid_manager.class%
        tags:
            - name: oro_grid.datagrid.manager
              datagrid_name: user_emails
              entity_name: Oro\Bundle\EmailBundle\Entity\Email
              query_entity_alias: email
              entity_hint: email
              route_name: oro_user_view

