Oro\Bundle\EmailBundle\Entity\EmailTemplate:
    name:                               entity.email_template.name
    description:                        entity.email_template.description

Oro\Bundle\EmailBundle\Entity\Email:
    icon_class:                         icon-envelope
    name:                               entity.email.name
    description:                        entity.email.description
