Oro\Bundle\EmailBundle\Entity\EmailTemplate:
    icon_class:                         icon-envelope
    name:                               entity.email_template.name
    description:                        entity.email_template.description

