oro_entity_config:
    email:
        field:
            items:
                available_in_template:
                    options:
                        default_value:      false
                        allowed_type:       [string,integer,smallint,bigint,boolean,decimal,date,text,float]
                        is_bool:            true
                    form:
                        type:               choice
                        options:
                            choices:        ['No', 'Yes']
                            empty_value:    false
                            block:          other
                            label:          'Available in email templates'
