parameters:
    oro_email.form.subscriber.emailtemplate.class:        Oro\Bundle\EmailBundle\Form\EventListener\BuildTemplateFormSubscriber
    oro_email.form.type.emailtemplate.class:              Oro\Bundle\EmailBundle\Form\Type\EmailTemplateType
    oro_email.form.type.emailtemplate_select.class:       Oro\Bundle\EmailBundle\Form\Type\EmailTemplateSelectType
    oro_email.form.type.emailtemplate_translation.class:  Oro\Bundle\EmailBundle\Form\Type\EmailTemplateTranslationType
    oro_email.form.handler.emailtemplate.class:           Oro\Bundle\EmailBundle\Form\Handler\EmailTemplateHandler
    oro_email.form.type.emailtemplate.api.class:          Oro\Bundle\EmailBundle\Form\Type\EmailTemplateApiType
    oro_email.form.handler.email.class:                   Oro\Bundle\EmailBundle\Form\Handler\EmailHandler
    oro_email.form.handler.email.api.class:               Oro\Bundle\EmailBundle\Form\Handler\EmailApiHandler
    oro_email.form.type.email.class:                      Oro\Bundle\EmailBundle\Form\Type\EmailType
    oro_email.form.type.email.api.class:                  Oro\Bundle\EmailBundle\Form\Type\EmailApiType
    oro_email.form.type.email_folder.api.class:           Oro\Bundle\EmailBundle\Form\Type\EmailFolderApiType
    oro_email.form.type.email_address.class:              Oro\Bundle\EmailBundle\Form\Type\EmailAddressType
    oro_email.form.type.email_address.api.class:          Oro\Bundle\EmailBundle\Form\Type\EmailAddressApiType
    oro_email.form.type.attachment.class:                 Oro\Bundle\EmailBundle\Form\Type\EmailAttachmentType
    oro_email.form.type.attachments.class:                Oro\Bundle\EmailBundle\Form\Type\EmailAttachmentsType
    oro_email.form.type.contexts_select.class:            Oro\Bundle\EmailBundle\Form\Type\ContextsSelectType
    oro_email.form.type.email_link_to_scope.class:        Oro\Bundle\EmailBundle\Form\Type\EmailLinkToScopeType
    oro_email.form.type.mailbox_grid.class:               Oro\Bundle\EmailBundle\Form\Type\MailboxGridType
    oro_email.form.type.mailbox.class:                    Oro\Bundle\EmailBundle\Form\Type\MailboxType
    oro_email.form.type.smtp.class:                       Oro\Bundle\EmailBundle\Form\Type\SmtpType
    oro_email.form.type.mailbox_processor_manual.class:   Oro\Bundle\EmailBundle\Form\Type\ManualMailboxProcessorType
    oro_email.form.factory.class:                         Oro\Bundle\EmailBundle\Form\Model\Factory
    oro_email.form.type.email_folder.class:               Oro\Bundle\EmailBundle\Form\Type\EmailFolderType
    oro_email.form.type.email_folder_tree.class:          Oro\Bundle\EmailBundle\Form\Type\EmailFolderTreeType
    oro_email.form.type.filter.originfolder.class:        Oro\Bundle\EmailBundle\Form\Type\Filter\ChoiceOriginFolderFilterType

services:
    oro_email.form.subscriber.emailtemplate:
        class: %oro_email.form.subscriber.emailtemplate.class%
        arguments:
            - @security.context

    oro_email.form.emailtemplate:
        class: Symfony\Component\Form\Form
        factory_method: createNamed
        factory_service: form.factory
        arguments: ["oro_email_emailtemplate", "oro_email_emailtemplate", null]

    oro_email.form.type.emailtemplate:
        class: %oro_email.form.type.emailtemplate.class%
        arguments:
            - @oro_config.user
            - @oro_locale.settings
        tags:
            - { name: form.type, alias: oro_email_emailtemplate }

    oro_email.form.type.emailtemplate_translation:
        class: %oro_email.form.type.emailtemplate_translation.class%
        arguments:
            - @oro_config.user
        tags:
            - { name: form.type, alias: oro_email_emailtemplate_translatation }

    oro_email.form.type.emailtemplate_select:
        class: %oro_email.form.type.emailtemplate_select.class%
        tags:
            - { name: form.type, alias: oro_email_template_list }

    oro_email.form.handler.emailtemplate:
        class: %oro_email.form.handler.emailtemplate.class%
        scope: request
        arguments:
            - @oro_email.form.emailtemplate
            - @request
            - @doctrine.orm.entity_manager
            - @translator
        calls:
            - [setDefaultLocale, [%stof_doctrine_extensions.default_locale%]]

    oro_email.form.handler.email:
        class: %oro_email.form.handler.email.class%
        scope: request
        arguments:
            - @oro_email.form.email
            - @request
            - @oro_email.mailer.processor
            - @logger

    oro_email.form.email:
        class: Symfony\Component\Form\Form
        factory_method: createNamed
        factory_service: form.factory
        arguments: ["oro_email_email", "oro_email_email", null]

    oro_email.form.type.email:
        class: %oro_email.form.type.email.class%
        arguments:
            - @security.context
        tags:
            - { name: form.type, alias: oro_email_email }

    oro_email.form.handler.email.api:
        class: %oro_email.form.handler.email.api.class%
        scope: request
        arguments:
            - @oro_email.form.email.api
            - @request
            - @doctrine.orm.entity_manager
            - @oro_email.email.entity.builder=
            - @oro_security.security_facade
            - @event_dispatcher
            - @oro_email.email_importance_transformer
            - @oro_email.email_body_type_transformer

    oro_email.form.email.api:
        class: Symfony\Component\Form\Form
        factory_method: createNamed
        factory_service: form.factory
        arguments:
            - ~
            - 'oro_email_email_api'

    oro_email.form.type.email.api:
        class: %oro_email.form.type.email.api.class%
        tags:
            - { name: form.type, alias: oro_email_email_api }

    oro_email.form.type.email_folder.api:
        class: %oro_email.form.type.email_folder.api.class%
        tags:
            - { name: form.type, alias: oro_email_email_folder_api }

    oro_email.form.type.email_address:
        class: %oro_email.form.type.email_address.class%
        tags:
            - { name: form.type, alias: oro_email_email_address }

    oro_email.form.type.email_address.api:
        class: %oro_email.form.type.email_address.api.class%
        tags:
            - { name: form.type, alias: oro_email_email_address_api }

    oro_email.form.type.attachment:
        class: %oro_email.form.type.attachment.class%
        arguments:
            - @doctrine.orm.entity_manager
            - @oro_email.email_attachment_transformer
        tags:
            - { name: form.type, alias: oro_email_attachment }

    oro_email.form.type.attachments:
        class: %oro_email.form.type.attachments.class%
        tags:
            - { name: form.type, alias: oro_email_attachments }

    oro_email.form.type.contexts_select:
        class: %oro_email.form.type.contexts_select.class%
        arguments:
            - @doctrine.orm.entity_manager
        tags:
            - { name: form.type, alias: oro_email_contexts_select }

    oro_email.form.type.email_link_to_scope:
        class: %oro_email.form.type.email_link_to_scope.class%
        tags:
            - { name: form.type, alias: oro_email_link_to_scope }

    oro_email.form.type.mailbox_grid:
        class: %oro_email.form.type.mailbox_grid.class%
        tags:
            - { name: form.type, alias: oro_email_mailbox_grid }

    oro_email.form.type.mailbox:
        class: %oro_email.form.type.mailbox.class%
        arguments: [@oro_email.provider.mailbox_processor_provider]
        tags:
            - { name: form.type, alias: oro_email_mailbox }

    oro_email.form.type.smtp:
        class: %oro_email.form.type.smtp.class%
        tags:
            - { name: form.type, alias: oro_email_smtp }

    oro_email.form.type.mailbox_processor_manual:
        class: %oro_email.form.type.mailbox_processor_manual.class%
        arguments: [@oro_email.provider.mailbox_processor_provider]
        tags:
            - { name: form.type, alias: oro_email_mailbox_processor_manual }

    oro_email.form.factory:
        class: %oro_email.form.factory.class%

    oro_email.form.type.email_folder:
        class: %oro_email.form.type.email_folder.class%
        tags:
            - { name: form.type, alias: oro_email_email_folder }

    oro_email.form.type.email_folder_tree:
        class: %oro_email.form.type.email_folder_tree.class%
        tags:
            - { name: form.type, alias: oro_email_email_folder_tree }

    oro_email.form.type.filter.originfolder:
        class: %oro_email.form.type.filter.originfolder.class%
        arguments: ["@translator"]
        tags:
            - { name: form.type, alias: oro_type_originfolder_filter }
