oro_menu_config:
    items:
        oro_email_emailtemplate_list:
            label: 'Email templates'
            route: 'oro_email_emailtemplate_index'
            extras:
                routes: ['oro_email_emailtemplate_*']
    tree:
        application_menu:
            children:
                system_tab:
                    children:
                        oro_email_emailtemplate_list: ~

oro_titles:
    oro_email_emailtemplate_index: ~
    oro_email_emailtemplate_update: "Edit template %%name%%"
    oro_email_emailtemplate_create: "Create email template"
    oro_email_emailtemplate_clone: "Clone email template"
