placeholders:
    dots_menu:
        items:
            dots_menu_email:
                order: 100
    scripts_before:
        items:
            email_filter_templates:
                order: 5

items:
    oro_send_email_button:
        template: OroEmailBundle:Email:activityButton.html.twig
        acl: oro_email_email_create
    oro_send_email_link:
        template: OroEmailBundle:Email:activityLink.html.twig
        acl: oro_email_email_create
    dots_menu_email:
        action: OroEmailBundle:Email:notificationData
        applicable: @oro_user.placeholder.filter->isUserApplicable()
    email_filter_templates:
        template: OroEmailBundle:Js:default_templates.js.twig
