placeholders:
    dots_menu:
        items:
            dots_menu_email:
                order: 100

items:
    oro_send_email_button:
        template: OroEmailBundle:Email:activityButton.html.twig
        acl: oro_email_email_create
    oro_send_email_link:
        template: OroEmailBundle:Email:activityLink.html.twig
        acl: oro_email_email_create
    dots_menu_email:
        template: OroEmailBundle:Notification:button.html.twig
        applicable: @oro_user.placeholder.filter->isUserApplicable()

