config:
    paths:
        'oroemail/js/app/models/email-template-collection': 'bundles/oroemail/js/app/models/email-template-collection.js'
        'oroemail/js/app/models/email-template-model': 'bundles/oroemail/js/app/models/email-template-model.js'
        'oroemail/js/app/views/email-template-view': 'bundles/oroemail/js/app/views/email-template-view.js'
        'oroemail/js/app/views/email-attachment-link-view': 'bundles/oroemail/js/app/views/email-attachment-link-view.js'
        'oroemail/js/app/components/email-context-component': 'bundles/oroemail/js/app/components/email-context-component.js'
        'oroemail/js/app/model/email-context-model': 'bundles/oroemail/js/app/model/email-context-model.js'
        'oroemail/js/app/model/email-context-collection': 'bundles/oroemail/js/app/model/email-context-collection.js'
        'oroemail/js/app/views/email-context-view': 'bundles/oroemail/js/app/views/email-context-view.js'
        'oroemail/js/app/components/email-context-activity-component': 'bundles/oroemail/js/app/components/email-context-activity-component.js'
        'oroemail/js/app/model/email-context-activity-model': 'bundles/oroemail/js/app/views/email-context-activity-model.js'
        'oroemail/js/app/model/email-context-activity-collection': 'bundles/oroemail/js/app/model/email-context-activity-collection.js'
        'oroemail/js/app/views/email-context-activity-view': 'bundles/oroemail/js/app/views/email-context-activity-view.js'

        'oroemail/js/app/components/email-variable-component': 'bundles/oroemail/js/app/components/email-variable-component.js'
        'oroemail/js/app/apply-template-confirmation': 'bundles/oroemail/js/app/apply-template-confirmation.js'
