oro_email:
    resource:     "@OroEmailBundle/Controller"
    type:         annotation
    prefix:       /email


oro_email_api:
    resource: Oro\Bundle\EmailBundle\Controller\Api\Rest\EmailTemplateController
    type: rest
    prefix: api/rest/{version}/
    requirements:
        version: latest|v1
    defaults:
        version: latest