parameters:
    oro_email.emailtemplate.entity.class: Oro\Bundle\EmailBundle\Entity\EmailTemplate

    # Email template field
    oro_email.form.subscriber.emailtemplate.class: Oro\Bundle\EmailBundle\Form\EventListener\BuildTemplateFormSubscriber

    # Email template forms
    oro_email.form.type.emailtemplate.class: Oro\Bundle\EmailBundle\Form\Type\EmailTemplateType
    oro_email.form.type.emailtemplate_select.class: Oro\Bundle\EmailBundle\Form\Type\EmailTemplateSelectType
    oro_email.form.type.emailtemplate_translation.class: Oro\Bundle\EmailBundle\Form\Type\EmailTemplateTranslationType
    oro_email.form.handler.emailtemplate.class: Oro\Bundle\EmailBundle\Form\Handler\EmailTemplateHandler

    # Email template API
    oro_email.manager.emailtemplate.api.class: Oro\Bundle\SoapBundle\Entity\Manager\ApiEntityManager
    oro_email.form.type.emailtemplate.api.class: Oro\Bundle\EmailBundle\Form\Type\EmailTemplateApiType

    # Entity config event listener
    oro_email.listener.config_subscriber.class: Oro\Bundle\EmailBundle\EventListener\ConfigSubscriber

    # Providers
    oro_email.provider.variable_provider.class: Oro\Bundle\EmailBundle\Provider\VariablesProvider

    # Cache keys
    oro_email.cache.available_in_template_key: 'oro_email.available_in_template_fields'

    # Email renderer, twig instance
    oro_email.email_renderer.class: Oro\Bundle\EmailBundle\Provider\EmailRenderer
    #oro_email.twig.email_security_policy.class: Oro\Bundle\EmailBundle\Provider\TwigSecurityPolicy
    oro_email.twig.email_security_policy.class: Twig_Sandbox_SecurityPolicy

services:
    # Email template field
    oro_email.form.subscriber.emailtemplate:
        class: %oro_email.form.subscriber.emailtemplate.class%
        arguments:
            - @doctrine.orm.entity_manager
            - @form.factory

    # Email template forms
    oro_email.form.emailtemplate:
            class: Symfony\Component\Form\Form
            factory_method: createNamed
            factory_service: form.factory
            arguments: ["oro_email_emailtemplate", "oro_email_emailtemplate", null]

    oro_email.form.type.emailtemplate:
        class: %oro_email.form.type.emailtemplate.class%
        arguments: [ %oro_config.entities% ]
        tags:
            - { name: form.type, alias: oro_email_emailtemplate }

    oro_email.form.type.emailtemplate_translation:
        class: %oro_email.form.type.emailtemplate_translation.class%
        tags:
            - { name: form.type, alias: oro_email_emailtemplate_translatation }

    oro_email.form.type.emailtemplate_select:
        class: %oro_email.form.type.emailtemplate_select.class%
        tags:
            - { name: form.type, alias: oro_email_template_list }

    oro_email.form.handler.emailtemplate:
        class: %oro_email.form.handler.emailtemplate.class%
        scope: request
        arguments:
            - @oro_email.form.emailtemplate
            - @request
            - @doctrine.orm.entity_manager
            - @translator

    # Email template API
    oro_email.manager.emailtemplate.api:
        class: %oro_email.manager.emailtemplate.api.class%
        arguments:
            - %oro_email.emailtemplate.entity.class%
            - @doctrine.orm.entity_manager

    oro_email.form.type.emailtemplate.api:
        class: %oro_email.form.type.emailtemplate.api.class%
        arguments: [ %oro_config.entities% ]
        tags:
            - { name: form.type, alias: oro_email_emailtemplate_api }

    oro_email.form.emailtemplate.api:
        class: Symfony\Component\Form\Form
        factory_method: createNamed
        factory_service: form.factory
        arguments: ["oro_email_emailtemplate_api", "oro_email_emailtemplate_api", null]

    oro_email.form.handler.emailtemplate.api:
        class: %oro_email.form.handler.emailtemplate.class%
        scope: request
        arguments:
            - @oro_email.form.emailtemplate.api
            - @request
            - @doctrine.orm.entity_manager
            - @translator

    oro_email.cache:
          parent: oro.cache.abstract
          calls:
              - [setNamespace, ['oro_email.cache']]

    # Available variables services
    oro_email.listener.config_subscriber:
        class:      %oro_email.listener.config_subscriber.class%
        arguments:  [@oro_email.cache, %oro_email.cache.available_in_template_key%]
        tags:
            - { name: kernel.event_subscriber}

    # email template twig instance
    oro_email.twig.string_loader:
        class: Twig_Loader_String

    oro_email.email_renderer:
        class: %oro_email.email_renderer.class%
        arguments:
            - @oro_email.twig.string_loader
            - [] # twig environment options
            - @oro_email.config.available_in_templates
            - @oro_email.cache
            - %oro_email.cache.available_in_template_key%
            - @security.context
        calls:
            # add extension sandbox using method call and not twig.extension tag cause we need to add sandbox only to this instance
            - [ addExtension, [@oro_email.twig.email_sandbox] ]

    oro_email.twig.email_security_policy:
        class: %oro_email.twig.email_security_policy.class%
        arguments:
            # tags
            - [ 'if', 'app' ]
            # filters
            - [ 'upper', 'escape' ]
            # methods
            - []
            # properties
            - []
            # functions
            - []

    oro_email.twig.email_sandbox:
        class: Twig_Extension_Sandbox
        arguments:
            - @oro_email.twig.email_security_policy
            - true # use sandbox globally in instance

    oro_email.config.available_in_templates:
        tags:
            - { name: oro_entity_config.provider, scope: email }

    oro_email.provider.variable_provider:
        class: %oro_email.provider.variable_provider.class%
        arguments:
            - @security.context
            - @oro_email.config.available_in_templates

    oro_email.validator.variables_validator:
        class: Oro\Bundle\EmailBundle\Validator\VariablesValidator
        arguments:
            - @oro_notification.twig
            - @security.context
        tags:
            - { name: validator.constraint_validator, alias: oro_email.variables_validator }
