parameters:
    oro_email.email.entity.class:                 Oro\Bundle\EmailBundle\Entity\Email
    oro_email.email_folder.entity.class:          Oro\Bundle\EmailBundle\Entity\EmailFolder
    oro_email.email.cache.manager.class:          Oro\Bundle\EmailBundle\Cache\EmailCacheManager
    oro_email.email.address.manager.class:        Oro\Bundle\EmailBundle\Entity\Manager\EmailAddressManager
    oro_email.email.owner.provider.class:         Oro\Bundle\EmailBundle\Entity\Provider\EmailOwnerProvider
    oro_email.email.owner.provider.storage.class: Oro\Bundle\EmailBundle\Entity\Provider\EmailOwnerProviderStorage
    oro_email.email.owner.manager.class:          Oro\Bundle\EmailBundle\Entity\Manager\EmailOwnerManager
    oro_email.email.entity.builder.class:         Oro\Bundle\EmailBundle\Builder\EmailEntityBuilder
    oro_email.email.entity.batch_processor.class: Oro\Bundle\EmailBundle\Builder\EmailEntityBatchProcessor
    oro_email.email_body_loader_selector.class:   Oro\Bundle\EmailBundle\Provider\EmailBodyLoaderSelector
    oro_email.listener.entity_listener.class:     Oro\Bundle\EmailBundle\EventListener\EntityListener
    oro_email.manager.email.api.class:            Oro\Bundle\EmailBundle\Entity\Manager\EmailApiEntityManager
    oro_email.entity.cache.warmer.class:          Oro\Bundle\EmailBundle\Cache\EntityCacheWarmer
    oro_email.entity.cache.clearer.class:         Oro\Bundle\EmailBundle\Cache\EntityCacheClearer
    oro_email.direct_mailer.class:                Oro\Bundle\EmailBundle\Mailer\DirectMailer
    oro_email.mailer.processor.class:             Oro\Bundle\EmailBundle\Mailer\Processor
    oro_email.email_synchronization_manager.class:  Oro\Bundle\EmailBundle\Sync\EmailSynchronizationManager
    oro_email.event_listener.activity_grid_listener.class: Oro\Bundle\EmailBundle\EventListener\Datagrid\ActivityGridListener
    oro_email.listener.datagrid.myemails.class:   Oro\Bundle\EmailBundle\EventListener\Datagrid\MyEmailsGridListener

    oro_email.emailtemplate.entity.class: Oro\Bundle\EmailBundle\Entity\EmailTemplate

    # Email template API
    oro_email.manager.emailtemplate.api.class: Oro\Bundle\SoapBundle\Entity\Manager\ApiEntityManager

    # Entity config event listener
    oro_email.listener.config_subscriber.class: Oro\Bundle\EmailBundle\EventListener\ConfigSubscriber

    # Providers
    oro_email.provider.variable_provider.class: Oro\Bundle\EmailBundle\Provider\VariablesProvider

    # Cache keys
    oro_email.cache.available_in_template_key: 'oro_email.available_in_template_fields'

    # Email renderer, twig instance
    oro_email.email_renderer.class: Oro\Bundle\EmailBundle\Provider\EmailRenderer
    oro_email.twig.email_security_policy.class: Twig_Sandbox_SecurityPolicy

    oro_email.datagrid_query_factory.class: Oro\Bundle\EmailBundle\Datagrid\EmailQueryFactory

    oro_email.emailtemplate.datagrid_view_list.class: Oro\Bundle\EmailBundle\Datagrid\EmailTemplatesViewList
    oro_email.emailtemplate.datagrid_helper.class:    Oro\Bundle\EmailBundle\Datagrid\EmailTemplatesGridHelper

    # Datagrid event listeners
    oro_email.listener.datagrid.email.class: Oro\Bundle\EmailBundle\EventListener\Datagrid\EmailListener

    #Email Action for workflows
    oro_email.workflow.action.send_email.class: Oro\Bundle\EmailBundle\Workflow\Action\SendEmail

services:
    oro_email.entity.cache.warmer:
        class: %oro_email.entity.cache.warmer.class%
        arguments:
            - @oro_email.email.owner.provider.storage
            - %oro_email.entity.cache_dir%
            - %oro_email.entity.cache_namespace%
            - %oro_email.entity.proxy_name_template%
        tags:
            - { name: kernel.cache_warmer, priority: 30 }

    oro_email.entity.cache.clearer:
        class: %oro_email.entity.cache.clearer.class%
        arguments:
            - %oro_email.entity.cache_dir%
            - %oro_email.entity.proxy_name_template%
        tags:
            - { name: kernel.cache_clearer }

    oro_email.email.cache.manager:
        class: %oro_email.email.cache.manager.class%
        arguments:
            - @oro_email.email_body_loader_selector
            - @doctrine.orm.entity_manager

    oro_email.email_body_loader_selector:
        public: false
        class: %oro_email.email_body_loader_selector.class%

    oro_email.email.address.manager:
        class: %oro_email.email.address.manager.class%
        arguments:
            - %oro_email.entity.cache_namespace%
            - %oro_email.entity.proxy_name_template%

    oro_email.email.owner.provider.storage:
        public: false
        class: %oro_email.email.owner.provider.storage.class%

    oro_email.email.owner.provider:
        public: false
        class: %oro_email.email.owner.provider.class%
        arguments:
            - @oro_email.email.owner.provider.storage

    oro_email.email.owner.manager:
        public: false
        class: %oro_email.email.owner.manager.class%
        arguments:
            - @oro_email.email.owner.provider.storage
            - @oro_email.email.address.manager

    oro_email.email.entity.builder:
        class: %oro_email.email.entity.builder.class%
        scope: prototype
        arguments:
            - @oro_email.email.entity.batch_processor
            - @oro_email.email.address.manager

    oro_email.email.entity.batch_processor:
        class: %oro_email.email.entity.batch_processor.class%
        public: false
        scope: prototype
        arguments:
            - @oro_email.email.address.manager
            - @oro_email.email.owner.provider

    oro_email.listener.entity_listener:
        class: %oro_email.listener.entity_listener.class%
        arguments:
            - @oro_email.email.owner.manager
        tags:
            - { name: doctrine.event_listener, event: onFlush }

    oro_email.manager.email.api:
        class: %oro_email.manager.email.api.class%
        arguments:
            - %oro_email.email.entity.class%
            - @doctrine.orm.entity_manager

    oro_email.direct_mailer:
        class: %oro_email.direct_mailer.class%
        arguments:
            - @mailer
            - @service_container

    # Email template API
    oro_email.manager.emailtemplate.api:
        class: %oro_email.manager.emailtemplate.api.class%
        arguments:
            - %oro_email.emailtemplate.entity.class%
            - @doctrine.orm.entity_manager

    oro_email.cache:
          parent: oro.cache.abstract
          calls:
              - [setNamespace, ['oro_email.cache']]

    # Available variables services
    oro_email.listener.config_subscriber:
        class:      %oro_email.listener.config_subscriber.class%
        arguments:  [@oro_email.cache, %oro_email.cache.available_in_template_key%]
        tags:
            - { name: kernel.event_subscriber}

    # email template twig instance
    oro_email.twig.string_loader:
        class: Twig_Loader_String

    oro_email.email_renderer:
        class: %oro_email.email_renderer.class%
        arguments:
            - @oro_email.twig.string_loader
            -  # twig environment options
              strict_variables: true
            - @oro_entity_config.provider.email
            - @oro_email.cache
            - %oro_email.cache.available_in_template_key%
            - @security.context
            - @oro_email.twig.email_sandbox
        lazy: true

    oro_email.twig.email_security_policy:
        class: %oro_email.twig.email_security_policy.class%
        arguments:
            # tags
            - [ 'app', 'for', 'if', 'spaceless' ]
            # filters
            - [ 'default', 'date', 'escape', 'format', 'length', 'lower', 'nl2br', 'number_format', 'title', 'trim', 'upper' ]
            # methods
            - []
            # properties
            - []
            # functions
            - [ 'date' ]

    oro_email.twig.email_sandbox:
        class: Twig_Extension_Sandbox
        arguments:
            - @oro_email.twig.email_security_policy
            - true # use sandbox globally in instance

    oro_email.provider.variable_provider:
        class: %oro_email.provider.variable_provider.class%
        arguments:
            - @security.context
            - @oro_entity_config.provider.email
        lazy: true

    oro_email.validator.variables_validator:
        class: Oro\Bundle\EmailBundle\Validator\VariablesValidator
        arguments:
            - @oro_email.email_renderer
            - @security.context
            - @doctrine.orm.entity_manager
        tags:
            - { name: validator.constraint_validator, alias: oro_email.variables_validator }

    oro_email.datagrid_query_factory:
        class: %oro_email.datagrid_query_factory.class%
        arguments:
            - @doctrine
            - %oro_email.email.entity.class%
            - @oro_email.email.owner.provider.storage
            - @oro_config.user

    oro_email.emailtemplate.datagrid_view_list:
        class: %oro_email.emailtemplate.datagrid_view_list.class%
        arguments:
            - @translator

    oro_email.emailtemplate.datagrid_helper:
        class: %oro_email.emailtemplate.datagrid_helper.class%

    oro_email.mailer.processor:
        class: %oro_email.mailer.processor.class%
        arguments:
            - @doctrine.orm.entity_manager
            - @oro_email.email.entity.builder=
            - @oro_email.direct_mailer
            - @oro_email.email.owner.provider

    oro_email.workflow.action.send_email:
        class: %oro_email.workflow.action.send_email.class%
        arguments:
            - @oro_workflow.context_accessor
            - @oro_email.mailer.processor
            - @oro_locale.formatter.name
        tags:
            - { name: oro_workflow.action, alias: send_email }

    oro_email.listener.datagrid.email:
        class: %oro_email.listener.datagrid.email.class%
        arguments:
            - @oro_email.datagrid_query_factory
        tags:
            - { name: kernel.event_listener, event: oro_datagrid.datagrid.build.after.base-email-grid, method: onBuildAfter }

    oro_email.email_synchronization_manager:
        class: %oro_email.email_synchronization_manager.class%
        arguments:
            - @service_container

    oro_email.event_listener.activity_grid_listener:
        class: %oro_email.event_listener.activity_grid_listener.class%
        arguments:
            - @oro_activity.manager
        tags:
          - { name: kernel.event_listener, event: oro_datagrid.datagrid.build.after.activity-email-grid, method: onBuildAfter }

    oro_email.listener.datagrid.myemails:
        class: %oro_email.listener.datagrid.myemails.class%
        arguments:
            - @oro_email.datagrid_query_factory
        tags:
            - { name: kernel.event_listener, event: oro_datagrid.datagrid.build.after.my-emails-grid, method: onBuildAfter }
