parameters:
    oro_email.email.entity.class:                 Oro\Bundle\EmailBundle\Entity\Email
    oro_email.email.cache.manager.class:          Oro\Bundle\EmailBundle\Cache\EmailCacheManager
    oro_email.email.address.manager.class:        Oro\Bundle\EmailBundle\Entity\Manager\EmailAddressManager
    oro_email.email.owner.provider.class:         Oro\Bundle\EmailBundle\Entity\Provider\EmailOwnerProvider
    oro_email.email.owner.provider.storage.class: Oro\Bundle\EmailBundle\Entity\Provider\EmailOwnerProviderStorage
    oro_email.email.owner.manager.class:          Oro\Bundle\EmailBundle\Entity\Manager\EmailOwnerManager
    oro_email.email.entity.builder.class:         Oro\Bundle\EmailBundle\Builder\EmailEntityBuilder
    oro_email.email.entity.batch_processor.class: Oro\Bundle\EmailBundle\Builder\EmailEntityBatchProcessor
    oro_email.email_body_loader_selector.class:   Oro\Bundle\EmailBundle\Provider\EmailBodyLoaderSelector
    oro_email.listener.entity_subscriber.class:   Oro\Bundle\EmailBundle\EventListener\EntitySubscriber
    oro_email.manager.email.api.class:            Oro\Bundle\EmailBundle\Entity\Manager\EmailApiEntityManager
    oro_email.entity.cache.warmer.class:          Oro\Bundle\EmailBundle\Cache\EntityCacheWarmer
    oro_email.entity.cache.clearer.class:         Oro\Bundle\EmailBundle\Cache\EntityCacheClearer

    oro_email.emailtemplate.entity.class: Oro\Bundle\EmailBundle\Entity\EmailTemplate

    # Email template field
    oro_email.form.subscriber.emailtemplate.class: Oro\Bundle\EmailBundle\Form\EventListener\BuildTemplateFormSubscriber

    # Email template forms
    oro_email.form.type.emailtemplate.class: Oro\Bundle\EmailBundle\Form\Type\EmailTemplateType
    oro_email.form.type.emailtemplate_select.class: Oro\Bundle\EmailBundle\Form\Type\EmailTemplateSelectType
    oro_email.form.type.emailtemplate_translation.class: Oro\Bundle\EmailBundle\Form\Type\EmailTemplateTranslationType
    oro_email.form.handler.emailtemplate.class: Oro\Bundle\EmailBundle\Form\Handler\EmailTemplateHandler

    # Email template API
    oro_email.manager.emailtemplate.api.class: Oro\Bundle\SoapBundle\Entity\Manager\ApiEntityManager
    oro_email.form.type.emailtemplate.api.class: Oro\Bundle\EmailBundle\Form\Type\EmailTemplateApiType

    # Entity config event listener
    oro_email.listener.config_subscriber.class: Oro\Bundle\EmailBundle\EventListener\ConfigSubscriber

    # Providers
    oro_email.provider.variable_provider.class: Oro\Bundle\EmailBundle\Provider\VariablesProvider

    # Cache keys
    oro_email.cache.available_in_template_key: 'oro_email.available_in_template_fields'

    # Email renderer, twig instance
    oro_email.email_renderer.class: Oro\Bundle\EmailBundle\Provider\EmailRenderer
    oro_email.twig.email_security_policy.class: Twig_Sandbox_SecurityPolicy

    oro_email.datagrid_query_factory.class: Oro\Bundle\EmailBundle\Datagrid\EmailQueryFactory

    oro_email.emailtemplate.datagrid_view_list.class: Oro\Bundle\EmailBundle\Datagrid\EmailTemplatesViewList
    oro_email.emailtemplate.datagrid_helper.class:    Oro\Bundle\EmailBundle\Datagrid\EmailTemplatesGridHelper

services:
    oro_email.entity.cache.warmer:
        public: false
        class: %oro_email.entity.cache.warmer.class%
        arguments:
            - @oro_email.email.owner.provider.storage
            - %oro_email.entity.cache_dir%
            - %oro_email.entity.cache_namespace%
            - %oro_email.entity.proxy_name_template%
        tags:
            - { name: kernel.cache_warmer, priority: 30 }

    oro_email.entity.cache.clearer:
        public: false
        class: %oro_email.entity.cache.clearer.class%
        arguments:
            - %oro_email.entity.cache_dir%
            - %oro_email.entity.cache_namespace%
            - %oro_email.entity.proxy_name_template%
        tags:
            - { name: kernel.cache_clearer }

    oro_email.email.cache.manager:
        class: %oro_email.email.cache.manager.class%
        arguments:
            - @oro_email.email_body_loader_selector
            - @doctrine.orm.entity_manager

    oro_email.email_body_loader_selector:
        public: false
        class: %oro_email.email_body_loader_selector.class%

    oro_email.email.address.manager:
        class: %oro_email.email.address.manager.class%
        arguments:
            - %oro_email.entity.cache_namespace%
            - %oro_email.entity.proxy_name_template%

    oro_email.email.owner.provider.storage:
        public: false
        class: %oro_email.email.owner.provider.storage.class%

    oro_email.email.owner.provider:
        public: false
        class: %oro_email.email.owner.provider.class%
        arguments:
            - @oro_email.email.owner.provider.storage

    oro_email.email.owner.manager:
        public: false
        class: %oro_email.email.owner.manager.class%
        arguments:
            - @oro_email.email.owner.provider.storage
            - @oro_email.email.address.manager

    oro_email.email.entity.builder:
        class: %oro_email.email.entity.builder.class%
        scope: prototype
        arguments:
            - @oro_email.email.entity.batch_processor
            - @oro_email.email.address.manager

    oro_email.email.entity.batch_processor:
        class: %oro_email.email.entity.batch_processor.class%
        public: false
        scope: prototype
        arguments:
            - @oro_email.email.address.manager
            - @oro_email.email.owner.provider

    oro_email.listener.entity_subscriber:
        public: false
        class: %oro_email.listener.entity_subscriber.class%
        arguments:
            - @oro_email.email.owner.manager
        tags:
            - { name: doctrine.event_subscriber, connection: default }

    oro_email.manager.email.api:
        class: %oro_email.manager.email.api.class%
        arguments:
            - %oro_email.email.entity.class%
            - @doctrine.orm.entity_manager

    # Email template field
    oro_email.form.subscriber.emailtemplate:
        class: %oro_email.form.subscriber.emailtemplate.class%
        arguments:
            - @doctrine.orm.entity_manager
            - @form.factory

    # Email template forms
    oro_email.form.emailtemplate:
            class: Symfony\Component\Form\Form
            factory_method: createNamed
            factory_service: form.factory
            arguments: ["oro_email_emailtemplate", "oro_email_emailtemplate", null]

    oro_email.form.type.emailtemplate:
        class: %oro_email.form.type.emailtemplate.class%
        arguments: [ %oro_config.entities% ]
        tags:
            - { name: form.type, alias: oro_email_emailtemplate }

    oro_email.form.type.emailtemplate_translation:
        class: %oro_email.form.type.emailtemplate_translation.class%
        tags:
            - { name: form.type, alias: oro_email_emailtemplate_translatation }

    oro_email.form.type.emailtemplate_select:
        class: %oro_email.form.type.emailtemplate_select.class%
        tags:
            - { name: form.type, alias: oro_email_template_list }

    oro_email.form.handler.emailtemplate:
        class: %oro_email.form.handler.emailtemplate.class%
        scope: request
        arguments:
            - @oro_email.form.emailtemplate
            - @request
            - @doctrine.orm.entity_manager
            - @translator

    # Email template API
    oro_email.manager.emailtemplate.api:
        class: %oro_email.manager.emailtemplate.api.class%
        arguments:
            - %oro_email.emailtemplate.entity.class%
            - @doctrine.orm.entity_manager

    oro_email.form.type.emailtemplate.api:
        class: %oro_email.form.type.emailtemplate.api.class%
        arguments: [ %oro_config.entities% ]
        tags:
            - { name: form.type, alias: oro_email_emailtemplate_api }

    oro_email.form.emailtemplate.api:
        class: Symfony\Component\Form\Form
        factory_method: createNamed
        factory_service: form.factory
        arguments: ["oro_email_emailtemplate_api", "oro_email_emailtemplate_api", null]

    oro_email.form.handler.emailtemplate.api:
        class: %oro_email.form.handler.emailtemplate.class%
        scope: request
        arguments:
            - @oro_email.form.emailtemplate.api
            - @request
            - @doctrine.orm.entity_manager
            - @translator

    oro_email.cache:
          parent: oro.cache.abstract
          calls:
              - [setNamespace, ['oro_email.cache']]

    # Available variables services
    oro_email.listener.config_subscriber:
        class:      %oro_email.listener.config_subscriber.class%
        arguments:  [@oro_email.cache, %oro_email.cache.available_in_template_key%]
        tags:
            - { name: kernel.event_subscriber}

    # email template twig instance
    oro_email.twig.string_loader:
        class: Twig_Loader_String

    oro_email.email_renderer:
        class: %oro_email.email_renderer.class%
        arguments:
            - @oro_email.twig.string_loader
            -  # twig environment options
              strict_variables: true
            - @oro_entity_config.provider.email
            - @oro_email.cache
            - %oro_email.cache.available_in_template_key%
            - @security.context
            - @oro_email.twig.email_sandbox

    oro_email.twig.email_security_policy:
        class: %oro_email.twig.email_security_policy.class%
        arguments:
            # tags
            - [ 'app', 'for', 'if', 'spaceless' ]
            # filters
            - [ 'default', 'date', 'escape', 'format', 'length', 'lower', 'nl2br', 'number_format', 'title', 'trim', 'upper' ]
            # methods
            - []
            # properties
            - []
            # functions
            - [ 'date' ]

    oro_email.twig.email_sandbox:
        class: Twig_Extension_Sandbox
        arguments:
            - @oro_email.twig.email_security_policy
            - true # use sandbox globally in instance

    oro_email.provider.variable_provider:
        class: %oro_email.provider.variable_provider.class%
        arguments:
            - @security.context
            - @oro_entity_config.provider.email

    oro_email.validator.variables_validator:
        class: Oro\Bundle\EmailBundle\Validator\VariablesValidator
        arguments:
            - @oro_email.email_renderer
            - @security.context
        tags:
            - { name: validator.constraint_validator, alias: oro_email.variables_validator }

    oro_email.datagrid_query_factory:
        class: %oro_email.datagrid_query_factory.class%
        arguments:
            - @doctrine
            - %oro_email.email.entity.class%
            - @oro_email.email.owner.provider.storage
            - @oro_config.user

    oro_email.emailtemplate.datagrid_view_list:
        class: %oro_email.emailtemplate.datagrid_view_list.class%
        arguments:
            - @translator

    oro_email.emailtemplate.datagrid_helper:
        class: %oro_email.emailtemplate.datagrid_helper.class%
        arguments: [%oro_config.entities%]
