oro_system_configuration:
    groups:
        email_configuration:
            icon:  icon-envelope
            title: oro.email.system_configuration.email_configuration
        signature_configuration:
            title: oro.email.system_configuration.signature_configuration.label
    fields:
        oro_email.signature:
            data_type: string
            type: oro_rich_text
            options:
                label: oro.email.system_configuration.signature_configuration.signature.label

    tree:
        system_configuration:
            platform:
                children:
                    general_setup:
                        children:
                            email_configuration:
                                children:
                                    signature_configuration:
                                        children:
                                            - oro_email.signature

    api_tree:
        signature_configuration:
            oro_email.signature: ~
