oro_system_configuration:
    groups:
        email_configuration:
            icon:  icon-envelope
            title: oro.email.system_configuration.email_configuration
        email_thread_configuration:
            title: oro.email.system_configuration.email_thread_configuration.label

    fields:
        oro_email.enable_threads:
            data_type: boolean
            type: oro_config_checkbox
            options:
                label: oro.email.system_configuration.email_thread_configuration.enable_threads.label
        oro_email.use_threads_at_activities:
            data_type: boolean
            type: oro_config_checkbox
            options:
                label: oro.email.system_configuration.use_threads_at_activities.label

    tree:
        system_configuration:
            platform:
                children:
                    general_setup:
                        children:
                            email_configuration:
                                children:
                                    email_thread_configuration:
                                        children:
                                            - oro_email.enable_threads
                            look_and_feel:
                                children:
                                    activity_list_settings:
                                        children:
                                            - oro_email.use_threads_at_activities

    api_tree:
        email_thread_configuration:
            oro_email.enable_threads: ~
        activity_list:
            oro_email.use_threads_at_activities: ~
