oro_system_configuration:
    groups:
        email_configuration:
            icon:  icon-envelope
            title: oro.email.system_configuration.email_configuration

        signature_configuration:
            title: oro.email.system_configuration.signature_configuration.label
            priority: 100

        email_threads:
            title: oro.email.system_configuration.email_threads.label
            priority: 90

        attachment_configuration:
            title: oro.email.system_configuration.attachment_configuration.label
            priority: 110

        reply_configuration:
            title: oro.email.system_configuration.reply_configuration.label
            priority: 80

    fields:
        oro_email.signature:
            data_type: string
            type: oro_rich_text
            options:
                label: oro.email.system_configuration.signature_configuration.signature.label
                required: false

        oro_email.append_signature:
            data_type: boolean
            type: choice
            options:
                label: oro.email.system_configuration.signature_configuration.append_signature.label
                choices:
                    1: oro.email.system_configuration.signature_configuration.append_signature.choices.auto.label
                    0: oro.email.system_configuration.signature_configuration.append_signature.choices.manual.label

        oro_email.default_button_reply:
            data_type: integer
            type: choice
            options:
                label: oro.email.system_configuration.reply_configuration.default_button.label
                choices:
                    1: oro.email.reply
                    2: oro.email.reply_all
                required: false

    tree:
        system_configuration:
            platform:
                children:
                    general_setup:
                        children:
                            email_configuration:
                                children:
                                    signature_configuration:
                                        children:
                                            - oro_email.signature
                                            - oro_email.append_signature
                                    reply_configuration:
                                        children:
                                            - oro_email.default_button_reply

    api_tree:
        signature_configuration:
            oro_email.signature: ~
            oro_email.append_signature: ~
        reply_configuration:
            oro_email.default_button_reply: ~
