features:
    email:
        label: oro.email.feature.label
        description: oro.email.feature.description
        toggle: oro_email.feature_enabled
        routes:
            - 'oro_email_autoresponserule_create'
            - 'oro_email_autoresponserule_update'
            - 'oro_email_purge_emails_attachments'
            - 'oro_email_view'
            - 'oro_email_last'
            - 'oro_email_thread_view'
            - 'oro_email_thread_widget'
            - 'oro_email_items_view'
            - 'oro_email_view_group'
            - 'oro_email_activity_view'
            - 'oro_email_email_create'
            - 'oro_email_email_reply'
            - 'oro_email_email_reply_all'
            - 'oro_email_email_forward'
            - 'oro_email_body'
            - 'oro_email_attachment'
            - 'oro_resize_email_attachment'
            - 'oro_email_body_attachments'
            - 'oro_email_attachment_link'
            - 'oro_email_widget_emails'
            - 'oro_email_widget_base_emails'
            - 'oro_email_user_emails'
            - 'oro_email_user_sync_emails'
            - 'oro_email_toggle_seen'
            - 'oro_email_mark_seen'
            - 'oro_email_mark_all_as_seen'
            - 'oro_email_mark_massaction'
            - 'oro_email_autocomplete_recipient'
            - 'oro_email_emailtemplate_index'
            - 'oro_email_emailtemplate_update'
            - 'oro_email_emailtemplate_create'
            - 'oro_email_emailtemplate_clone'
            - 'oro_email_emailtemplate_preview'
            - 'oro_email_emailorigin_list'
            - 'oro_email_dashboard_recent_emails'
            - 'oro_api_get_emails'
            - 'oro_api_get_email'
            - 'oro_api_put_email'
            - 'oro_api_post_email'
            - 'oro_api_options_emails'
            - 'oro_api_get_emailorigins'
            - 'oro_api_get_emailorigin'
            - 'oro_api_options_emailorigins'
            - 'oro_api_delete_emailtemplate'
            - 'oro_api_get_emailtemplates'
            - 'oro_api_get_emailtemplate_variables'
            - 'oro_api_get_emailtemplate_compiled'
            - 'oro_api_options_emailtemplates'
            - 'oro_api_get_email_activity_relations_by_filters'
            - 'oro_api_options_email_activity_relations'
            - 'oro_api_options_email_search_relations'
            - 'oro_api_get_activity_email_suggestions'
            - 'oro_api_options_activity_email_suggestions'
            - 'oro_email_mailbox_update'
            - 'oro_email_mailbox_create'
            - 'oro_email_mailbox_delete'
            - 'oro_email_mailbox_users_search'
            - 'oro_user_reset_send_email'
            - 'oro_user_reset_send_email_as_admin'
            - 'oro_user_reset_check_email'
            - 'oro_api_get_email_activity_relations'
            - 'oro_api_get_email_search_relations'
            - 'oro_notification_emailnotification_index'
            - 'oro_notification_emailnotification_update'
            - 'oro_notification_emailnotification_create'
            - 'oro_api_delete_emailnotication'
            - 'oro_api_options_emailnotications'
            - 'oro_account_frontend_account_user_confirmation'
            - 'oro_account_frontend_account_user_reset_check_email'
            - 'oro_email_autoresponserule_edittemplate'
        configuration:
            - 'email_autocomplete_configuration'
            - 'signature_configuration'
            - 'email_threads'
            - 'reply_configuration'
            - 'attachment_configuration'
            - 'template_configuration'
            - 'mailboxes'
            - 'user_mailbox'
            - 'user_bar_settings'
            - 'email_notifications_settings'
            - 'email_mass_notifications_settings'



